### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by ralienpp** [roataway/web-ui#176]
Between today and the time the project was last touched - it seems that some things changed in a way that makes the instructions incomplete. After cloning the repo, running `nmp install` and then `npm start` - I get this error:

```
Starting the development server...                                                                                                                                                  [12/12]
                                                                              
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)                                                                                                           
    at Object.createHash (node:crypto:139:10)                                                                                                               
    at module.exports (/home/gpstrack/roataway-web/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/gpstrack/roataway-web/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/gpstrack/roataway-web/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/gpstrack/roataway-web/node_modules/webpack/lib/NormalModule.js:503:5       
    at /home/gpstrack/roataway-web/node_modules/webpack/lib/NormalModule.js:358:12                         
    at /home/gpstrack/roataway-web/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/gpstrack/roataway-web/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/gpstrack/roataway-web/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
Browserslist: caniuse-lite is outdated. Please run:        
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
/home/gpstrack/roataway-web/node_modules/react-scripts/scripts/start.js:19
  throw err;                      
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)                             
    at Object.createHash (node:crypto:139:10)
    at module.exports (/home/gpstrack/roataway-web/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/gpstrack/roataway-web/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/gpstrack/roataway-web/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/gpstrack/roataway-web/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/gpstrack/roataway-web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/gpstrack/roataway-web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/gpstrack/roataway-web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/gpstrack/roataway-web/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [             
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],                                                                          
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'      
}                                        

Node.js v20.12.2  
```

The OS is Ubuntu LTS 22.04.

**Comment by unrevised6419** [comment]
I remember such a similar error a long time ago. It was related to the installed node version 🤔 

Try these steps:

- Install [nvm](https://github.com/nvm-sh/nvm)
- Run `nvm use` in project root.
- Remove `node_modules`
- Run `npm install`

**Comment by ralienpp** [comment]
Thanks! The required version is 16, whereas I used a newer one.
